site_name: Expense Scanner User Guide
theme:
  name: material


# This tells MkDocs where your Markdown source files are located.
# '.' means the Markdown files are in the same directory as mkdocs.yml
docs_dir: docs/

nav:
  - Home: index.md
  - All Modules:
    - Company Admin:
        - Introduction: "company admin/Introduction.md"
        - Dashboard: "company admin/Dashboard.md"
        - Organization:
          - Departments: "company admin/Organization/Departments.md"
          - Company Roles: "company admin/Organization/Company Roles.md"
          - Users: "company admin/Organization/Users.md"
        - Configuration:
            - Approval Matrix: "company admin/Configuration/Approval Matrix.md"
            - Categories: "company admin/Configuration/Categories.md"
        - Engagement:
          - Cost Center: "company admin/Engagement/Cost Center.md"
          - Projects: "company admin/Engagement/Projects.md"
          - Stakeholders: "company admin/Engagement/Stakeholders.md"
        - Reports: "company admin/Reports.md"
        - Vouchers: 
          - Dashboard: "company admin/Vouchers/Dashboard.md"
          - Manage Vouchers: "company admin/Vouchers/Manage Vouchers.md"
          - Return Requests: "company admin/Vouchers/Return Requests.md"
        - Notifications: "company admin/Notifications.md"
        - Settings: "company admin/Settings.md"
    
    - Employee:
        - Introduction: "employee/Introduction.md"
        - Dashboard: "employee/Dashboard.md"
        - My Expenses:
            - Add Expenses: "employee/My Expenses/Add Expenses.md"
            - My Expenses: "employee/My Expenses/My Expenses.md"
        - Create Report: "employee/Create Report.md"
        - Reports: "employee/Reports.md"
        - Advance Cash: "employee/Advance Cash.md"
        - Pending Approvals:
             - Overview: "employee/Pending Approvals/Overview.md"
             - Pending Approvals Card: "employee/Pending Approvals/Pending Approvals Card.md"
        - Settings:
             - Help & Support: "employee/Settings/Help & Support.md"
             - Settings: "employee/Settings/Settings.md"
             - Preferences: "employee/Settings/Preferences.md"

    - Users:
        - Introduction: "users/Introduction.md"
        - Dashboard Overview: "users/Dashboard Overview.md"
        - Settings: "users/Settings.md"
        - Create Expense Report: "users/Create Expense Report.md"
        - Scan Receipt: "users/Scan Receipt.md"
        - Expenses: "users/Expenses.md"
        - Reports: "users/Reports.md"
        
